### ISSUE TITLE
How to change the code of shift module to adapt cuda10?

### ISSUE THREAD

**Issue by Lyndsey-Xing** [kchengiva/Shift-GCN#1]
Hello,
I am very interested in your work. My environment is cuda10 instead of cuda9,  now I want to use your Temporal_shift module, how can I get it?  

Thanks, I am very eager to receive your advice.

**Comment by Anirudh257** [comment]
Hi, I also have cuda10.2 but it works properly for me. Maybe, you need Python3.7 version.

**Comment by kchengiva** [comment]
Thanks for your interest. 
I only test the code in pytorch0.4.1/cuda9.0/g++5.4.0, so I do not know whether the code has correct execution in other environment. If the compile is correct, it will print `Finished processing dependencies for shift-cuda-linear-cpp==0.0.0`, and the demo in `./model/Temporal_shift/demo.py` will be executed correctly and print the forward and backward results of an example tensor.

**Comment by Lyndsey-Xing** [comment]
> Hi, I also have cuda10.2 but it works properly for me. Maybe, you need Python3.7 version.

Thanks, I can run the code in Python3.7, but there is a new error "No module named 'shift_cuda' ". The code here refers to “cuda/shift_cuda.cpp”？ How can I tackle this error?  Thanks

**Comment by Anirudh257** [comment]
> > Hi, I also have cuda10.2 but it works properly for me. Maybe, you need Python3.7 version.
> 
> Thanks, I can run the code in Python3.7, but there is a new error "No module named 'shift_cuda' ". The code here refers to “cuda/shift_cuda.cpp”？ How can I tackle this error? Thanks

I am not sure. You can try with Python3.5 and Python3.6 as well. Follow the steps mentioned by the author.

**Comment by Lyndsey-Xing** [comment]
> > > Hi, I also have cuda10.2 but it works properly for me. Maybe, you need Python3.7 version.
> > 
> > 
> > Thanks, I can run the code in Python3.7, but there is a new error "No module named 'shift_cuda' ". The code here refers to “cuda/shift_cuda.cpp”？ How can I tackle this error? Thanks
> 
> I am not sure. You can try with Python3.5 and Python3.6 as well. Follow the steps mentioned by the author.

Thanks for your patient reply. 
I change my environment in Python3.7 that you can work well, but there comes a new error. So I mean you don't meet the error in Python3.7?

**Comment by Anirudh257** [comment]
No, I am not facing the error there. I am able to run it successfully in Python3.5 as well and I am sticking to Python3.5 only as of now. Maybe, you can try repeating the steps in a virtual environment with Python3.5 installed.

**Comment by Lyndsey-Xing** [comment]
> No, I am not facing the error there. I am able to run it successfully in Python3.5 as well and I am sticking to Python3.5 only as of now. Maybe, you can try repeating the steps in a virtual environment with Python3.5 installed.

Thanks. I'll try again.

**Comment by Lyndsey-Xing** [comment]
> Thanks for your interest.
> I only test the code in pytorch0.4.1/cuda9.0/g++5.4.0, so I do not know whether the code has correct execution in other environment. If the compile is correct, it will print `Finished processing dependencies for shift-cuda-linear-cpp==0.0.0`, and the demo in `./model/Temporal_shift/demo.py` will be executed correctly and print the forward and backward results of an example tensor.

Hello, thanks for your reply. 
My problem is when I run 'bash run.sh', I get an error "No module named 'shift_cuda'", this code is in shift.py line 5 'import shift_cuda '.  In my experience, maybe something is missing leads to this error, not an environmental problem.  Besides, I can run the code of 'Data Preparation'.
Please give me some advice to tackle this problem, thanks.

**Comment by kchengiva** [comment]
After compile, there should be a directory called `ANACONDA_PATH/lib/python3.6/site-packages/shift_cuda_linear_cpp-0.0.0-py3.6-linux-x86_64.egg`, where `ANACONDA_PATH` is your anaconda path. This directory contains the compiled files:
        -shift_cuda_linear_cpp-0.0.0-py3.6-linux-x86_64.egg\  
          -EGG-INFO\  
          -__pycache__\
          -shift_cuda.cpython-36m-x86_64-linux-gnu.so
          -shift_cuda.py
where `shift_cuda.cpython-36m-x86_64-linux-gnu.so` is the compiled file, and `shift_cuda.py` is the file you mentioned, it is not the `./model/Temporal_shift/cuda/shift_cuda.cpp`.

If you do not fine the above files in your `ANACONDA_PATH/lib/python3.6/site-packages/`, I think your compiling is not completed successfully. Because the error does not occur in my environment (`python3.6/pytorch0.4.1/cuda9.0/g++5.4.0`), it is hard for me to provide advise. You can refer to my environment, or try the environment as mentioned by Anirudh257.

**Comment by Lyndsey-Xing** [comment]
Thanks for your quite reply.
I change the  Server，it works for me. My new environment(python3.6/pytorch1.1/cuda10/g++5.5) is the same as my last server environment. So I still don't know what went wrong. If I know what the problem is in the future, I will come back and give feedback.

**Comment by xiaoiker** [comment]
I get this: 

Finished processing dependencies for shift-cuda-linear-cpp==0.0.0

Then while ran the demo.py
import shift_cuda
ImportError: /users/.local/lib/python3.6/site-packages/shift_cuda_linear_cpp-0.0.0-py3.6-linux-x86_64.egg/shift_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaRegisterFatBinaryEnd

gcc 7.4 Cuda10.
Unfortunately, all these are lowest version. Any suggestions?

**Comment by Lyndsey-Xing** [comment]
> I get this:
> 
> Finished processing dependencies for shift-cuda-linear-cpp==0.0.0
> 
> Then while ran the demo.py
> import shift_cuda
> ImportError: /users/.local/lib/python3.6/site-packages/shift_cuda_linear_cpp-0.0.0-py3.6-linux-x86_64.egg/shift_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaRegisterFatBinaryEnd
> 
> gcc 7.4 Cuda10.
> Unfortunately, all these are lowest version. Any suggestions?

Oh, happy to meet you here. 
My new environment(python36/pytorch11/cuda10/g++5.5) works well, you can try it. 
I still don't know why my last environment was wrong. These two environments are the same(python36/pytorch11/cuda10/g++5.5).

**Comment by kchengiva** [comment]
The error `undefined symbol: __cudaRegisterFatBinaryEnd` also occurs in some other cuda extension programs, such as [DCNv2](https://github.com/xingyizhou/CenterNet/issues/67) and [nms](https://github.com/open-mmlab/mmdetection/issues/385). You can refer to these discussions, which may solve your problem @xiaoiker .
In these discussion, it seems the problem is caused by incompatibility environment. As far as I know, `python3.6/pytorch0.4.1/cuda9.0/g++5.4.0` works well. As mentioned by Lyndsey-Xing and Anirudh257, `pytorch11/cuda10/g++5.5` may also works.

**Comment by xiaoiker** [comment]
@Lyndsey-Xing @kchengiva  Thanks for your help.

**Comment by thiagomcoutinho** [comment]
Hi, I'm trying to run you model but I'm having some trouble with the CUDA compilation. It's possible to you provide a docker file?

**Comment by kchengiva** [comment]
I'm sorry I couldn't be more helpful. We do not build docker file for this program.

**Comment by thiagomcoutinho** [comment]
Thanks for the fast reply! This [docker image](https://hub.docker.com/layers/pytorch/pytorch/1.1.0-cuda10.0-cudnn7.5-devel/images/sha256-1be771bff6d18ede7d98c171c577ae8fcbaf6f53b59a3e5fe5cee9e36e188fbc?context=explore) worked for me.

**Comment by kchengiva** [comment]
Glad to hear there is progress :)

**Comment by Guangjun-A** [comment]
> > Hi, I also have cuda10.2 but it works properly for me. Maybe, you need Python3.7 version.
> 
> Thanks, I can run the code in Python3.7, but there is a new error "No module named 'shift_cuda' ". The code here refers to “cuda/shift_cuda.cpp”？ How can I tackle this error? Thanks
@Lyndsey-Xing 
I also meet a error  "No module named 'shift_cuda' ". Did you tackle this error？Please give me some advice to tackle this problem, thanks.

**Comment by Lyndsey-Xing** [comment]
@Guangjun-A   Maybe you can try a new environment(python36/pytorch11/cuda10/g++5.5).

**Comment by Guangjun-A** [comment]
> @Guangjun-A Maybe you can try a new environment(python36/pytorch11/cuda10/g++5.5).

Thanks for your reply!
I wiil try again.

**Comment by tjumfb** [comment]
I successfully run run.sh and get 

Finished processing dependencies for shift-cuda-linear-cpp==0.0.0, and the demo in ./model/Temporal_shift/demo.py will be executed correctly and print the forward and backward results of an example tensor.

However, when I run shift_gcn.py, I get
`>>> from cuda.shift import Shift
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cuda'
`

**Comment by Anirudh257** [comment]
@tjumfb You can try Python3.6 once.

**Comment by tiancai-call** [comment]
> I successfully run run.sh and get
> 
> Finished processing dependencies for shift-cuda-linear-cpp==0.0.0, and the demo in ./model/Temporal_shift/demo.py will be executed correctly and print the forward and backward results of an example tensor.
> 
> However, when I run shift_gcn.py, I get `>>> from cuda.shift import Shift Traceback (most recent call last): File "<stdin>", line 1, in <module> ModuleNotFoundError: No module named 'cuda'`

hi! Did you solve this problem?
