### ISSUE TITLE
Local/Non-Local shift

### ISSUE THREAD

**Issue by jjhoon713** [kchengiva/Shift-GCN#11]
Thanks for the great work.

it seems like "A" is never used in the model. 
https://github.com/kchengiva/Shift-GCN/blob/77625b04e8e9633ab9007b2e4a5eb70347bb113e/model/shift_gcn.py#L78

is this because the given model is non-local shift GCN version? Do you have any codes to modify this into local shift graph convolution?

thank you.

**Comment by kchengiva** [comment]
Thanks for your interest. The given Shift-GCN model contains non-local spatial shift and adaptive temporal shift. You can implement local spatial shift following [this](https://github.com/kchengiva/Shift-GCN/issues/5#issuecomment-662915911).
