### ISSUE TITLE
Calculating the FLOPs of the model

### ISSUE THREAD

**Issue by vivek87799** [kchengiva/Shift-GCN#12]
Dear @kchengiva,

Thank you very much for the supplement that you have provided to calculate the FLOPs.
To verify I tried to calculate FLOPs in ST-GCN as provided in the paper and getting the below results 

spatial convolution [(3 × (N C C1 + N N C1)) × T ]I am getting FLOPs around 2.0232G
Temporal convolution[ (9 × T C C1) × N] I am getting FLOPs around 4.98 G
FC Flops 15360
Total 7.01 G

It will be kind if you could guide me where I deviated from your calculation.

  |   |   |   |   | SFLOPs | TFLOPs | FC FLOPs | Total
-- | -- | -- | -- | -- | -- | -- | -- | --
  | C | C1 | T | N |   |   |   |  
0 | 3 | 64 | 300 | 25 | 40320000 | 12960000 |   |  
1 | 64 | 64 | 300 | 25 | 128160000 | 276480000 |   |  
2 | 64 | 64 | 300 | 25 | 128160000 | 276480000 |   |  
3 | 64 | 64 | 300 | 25 | 128160000 | 276480000 |   |  
4 | 64 | 128 | 150 | 25 | 128160000 | 276480000 |   |  
5 | 128 | 128 | 150 | 25 | 220320000 | 552960000 |   |  
6 | 128 | 128 | 150 | 25 | 220320000 | 552960000 |   |  
7 | 128 | 256 | 75 | 25 | 220320000 | 552960000 |   |  
8 | 256 | 256 | 75 | 25 | 404640000 | 1105920000 |   |  
9 | 256 | 256 | 75 | 25 | 404640000 | 1105920000 |   |  
  |   |   |   |   |   |   | 256 x60=(15360) |  
  |   |   |   |   | 2023200000 | 4989600000 | 15360 | 7012815360

**Comment by kchengiva** [comment]
Thanks for your interest. 
Firstly, the computation cost of temporal convolution is [(9 × T C1 C1) × N] instead of [(9 × T C C1) × N], which is 6.08G. 
Secondly, in the NTU RGB+D dataset, there are one or two people in each sample. For samples with only one person, the second person is padded with zeros. The skeleton graphs of these two people are computed respectively. So we need to multiply the computation cost by 2.
Thus the result is (2.0232 + 6.08) * 2 = 16.2G.

**Comment by vivek87799** [comment]
Thank you very much for your quick response.

**Comment by kchengiva** [comment]
For ST-GCN, the number of parameters in spatial convolution layer is [C*C1 + C1], the number of parameters in temporal convolution layer is [9*C1*C1 + C1], the number of parameters in FC layer is 256*60. The total parameter cost is 3.0M.
For Shift-GCN, the number of parameters in a spatial convolution layer is [C*C1 + C1 + N*C1], the number of parameters in a temporal convolution layer is [C1*C1 + C1 + 2C1], the number of parameters in FC layer is 256*60. The total parameter cost is 0.5M.

**Comment by vivek87799** [comment]
Dear @kchengiva,

That was very helpful.

Thanks for your quick response .

**Comment by preksha12** [comment]
I am not able to find where FLOPS are computed?

**Comment by klong121** [comment]
Thanks for your interest. @preksha12 
The code for calculating the computational cost of ST-GCN is as below:
```
import numpy as np 

channel = [[3,64],[64,64],[64,64],[64,64],[64,128],[128,128],[128,128],[128,256],[256,256],[256,256],]
temporal = [300,300,300,300,150,150,150,75,75,75]

# ST-GCN
Sflops = 0
Tflops = 0
for layer in range(len(channel)):
	Sflops += 3*(channel[layer][0]*channel[layer][1]*25 + channel[layer][1]*25*25)*temporal[layer]
	Tflops += 9*(temporal[layer]*25)*(channel[layer][1]*channel[layer][1])
fc = 256*60

print('ST-GCN')
print('spatial', Sflops*2/1e9)
print('temporal', Tflops*2/1e9)
print('1 stream', (Sflops+Tflops+fc)*2/1e9)
print('2 stream', (Sflops+Tflops+fc)/1e9*2*2)
print('4 stream', (Sflops+Tflops+fc)/1e9*2*4)
```

**Comment by kchengiva** [comment]
Thanks for your interest. @preksha12 
The code for calculating the computational cost of ST-GCN is as below:
```
import numpy as np 

channel = [[3,64],[64,64],[64,64],[64,64],[64,128],[128,128],[128,128],[128,256],[256,256],[256,256],]
temporal = [300,300,300,300,150,150,150,75,75,75]

# ST-GCN
Sflops = 0
Tflops = 0
for layer in range(len(channel)):
	Sflops += 3*(channel[layer][0]*channel[layer][1]*25 + channel[layer][1]*25*25)*temporal[layer]
	Tflops += 9*(temporal[layer]*25)*(channel[layer][1]*channel[layer][1])
fc = 256*60

print('ST-GCN')
print('spatial', Sflops*2/1e9)
print('temporal', Tflops*2/1e9)
print('1 stream', (Sflops+Tflops+fc)*2/1e9)
print('2 stream', (Sflops+Tflops+fc)/1e9*2*2)
print('4 stream', (Sflops+Tflops+fc)/1e9*2*4)
```

**Comment by preksha12** [comment]
> Thanks for your interest. @preksha12
> The code for calculating the computational cost of ST-GCN is as below:
> 
> ```
> import numpy as np 
> 
> channel = [[3,64],[64,64],[64,64],[64,64],[64,128],[128,128],[128,128],[128,256],[256,256],[256,256],]
> temporal = [300,300,300,300,150,150,150,75,75,75]
> 
> # ST-GCN
> Sflops = 0
> Tflops = 0
> for layer in range(len(channel)):
> 	Sflops += 3*(channel[layer][0]*channel[layer][1]*25 + channel[layer][1]*25*25)*temporal[layer]
> 	Tflops += 9*(temporal[layer]*25)*(channel[layer][1]*channel[layer][1])
> fc = 256*60
> 
> print('ST-GCN')
> print('spatial', Sflops*2/1e9)
> print('temporal', Tflops*2/1e9)
> print('1 stream', (Sflops+Tflops+fc)*2/1e9)
> print('2 stream', (Sflops+Tflops+fc)/1e9*2*2)
> print('4 stream', (Sflops+Tflops+fc)/1e9*2*4)
> ```
Thank you so much for your reply.

**Comment by preksha12** [comment]
Hello,
I also have doubt regarding how you have formulated these equations for FLOPS. How can we apply FLOPS formula for any other network?

> > Thanks for your interest. @preksha12
> > The code for calculating the computational cost of ST-GCN is as below:
> > ```
> > import numpy as np 
> > 
> > channel = [[3,64],[64,64],[64,64],[64,64],[64,128],[128,128],[128,128],[128,256],[256,256],[256,256],]
> > temporal = [300,300,300,300,150,150,150,75,75,75]
> > 
> > # ST-GCN
> > Sflops = 0
> > Tflops = 0
> > for layer in range(len(channel)):
> > 	Sflops += 3*(channel[layer][0]*channel[layer][1]*25 + channel[layer][1]*25*25)*temporal[layer]
> > 	Tflops += 9*(temporal[layer]*25)*(channel[layer][1]*channel[layer][1])
> > fc = 256*60
> > 
> > print('ST-GCN')
> > print('spatial', Sflops*2/1e9)
> > print('temporal', Tflops*2/1e9)
> > print('1 stream', (Sflops+Tflops+fc)*2/1e9)
> > print('2 stream', (Sflops+Tflops+fc)/1e9*2*2)
> > print('4 stream', (Sflops+Tflops+fc)/1e9*2*4)
> > ```
> 
> Thank you so much for your reply.

Hello,
I also have doubt regarding how you have formulated these equations for FLOPS. How can we apply FLOPS formula for any other network?
