### ISSUE TITLE
Results of four streams on NTU RGB+D 60

### ISSUE THREAD

**Issue by Viozer** [kchengiva/Shift-GCN#15]
Hi, thanks for sharing your code. Could you report your results of four streams on NTU RGB+D 60 respectively? I experiment with motion data but the accuracy is 1%~2% lower than the corresponding original data. I don't know if this is normal. BTW, I process the motion data online as below because gen_motion_data.py takes a long time.(computing motion data in __getitem__() of feeder). Will it affect model performance? 

    def __getitem__(self, index):
        if self.motion:
            C, T, V, M = data_numpy.shape
            data_numpy[:, :T-1] = data_numpy[:, 1:T] - data_numpy[:, :T-1]
            data_numpy[:, T-1] = 0
        if self.normalization:
            data_numpy = (data_numpy - self.mean_map) / self.std_map
        if self.random_shift:
            data_numpy = tools.random_shift(data_numpy)
        if self.random_choose:
            data_numpy = tools.random_choose(data_numpy, self.window_size)
        elif self.window_size > 0:
            data_numpy = tools.auto_pading(data_numpy, self.window_size)
        if self.random_move:
            data_numpy = tools.random_move(data_numpy)

        return data_numpy, label, index

**Comment by kchengiva** [comment]
Thanks for your interest. 
The accuracy of motion stream is typically 1-2% lower than the corresponding original data. The accuracy of four streams on NTU RGB+D Xsub task are as below:

Stream|Top-1(%)
-|-
joint|87.8
bone|88.0
joint motion|86.7
bone motion|86.5
