### ISSUE TITLE
Seems the information of skeleton graph is not used

### ISSUE THREAD

**Issue by SupetZYK** [kchengiva/Shift-GCN#16]
Why is the information of the skeleton graph is not used?

**Comment by kchengiva** [comment]
Thanks for your interest. The given Shift-GCN model uses non-local spatial shift, which does not need pre-defined skeleton graph. Please refer to our [paper](https://openaccess.thecvf.com/content_CVPR_2020/papers/Cheng_Skeleton-Based_Action_Recognition_With_Shift_Graph_Convolutional_Network_CVPR_2020_paper.pdf).

**Comment by YanjunChen** [comment]
> Thanks for your interest. The given Shift-GCN model uses non-local spatial shift, which does not need pre-defined skeleton graph. Please refer to our [paper](https://openaccess.thecvf.com/content_CVPR_2020/papers/Cheng_Skeleton-Based_Action_Recognition_With_Shift_Graph_Convolutional_Network_CVPR_2020_paper.pdf).

I am wondering if there is no GCN implemented, since all is shift + point-wise calculation, would it be more proper to Shift-Conv than Shift-GCN ?
