### ISSUE TITLE
Adaptive temporal shift graph convolution

### ISSUE THREAD

**Issue by vivek87799** [kchengiva/Shift-GCN#19]
Dear @kchengiva,
Your work is very impressive. 

I have some doubts in adaptive temporal shift graph convolution. 
It will be very kind if you could explain the equation, 
Fe(v,t,i) = (1 − λ) · F(v,⌊t+Si⌋,i) + λ · F(v,⌊t+Si⌋+1,i)

**Comment by kchengiva** [comment]
Thanks for your interest. 
In this equation, the output feature is linear interpolation between two frames. Please refer to the defination of linear interpolation, and refer to our paper for notations.

**Comment by YanjunChen** [comment]
> Thanks for your interest.
> In this equation, the output feature is linear interpolation between two frames. Please refer to the defination of linear interpolation, and refer to our paper for notations.

So the interpolation is only within the consecutive two frames?  or interpolation within the whole video?
