### ISSUE TITLE
Recovery Training

### ISSUE THREAD

**Issue by Nancyuru** [kchengiva/Shift-GCN#20]
Dear Kchengiva，
Hello, when I was training the model, the network error caused the training to be interrupted. I see you saved the model in the. pt file, and I want to ask how to resume the training. thank you.Looking forward to your reply.

**Comment by kchengiva** [comment]
Thanks for your interest. For example, if you want to load the .pt file in NTU-Xview task, you can add `weights: the trained model .pt file` and `start_epoch: your interrupted epoch number` in `./config/nturgbd-cross-view/train_joint.yaml` , then run `python main.py --config ./config/nturgbd-cross-view/train_joint.yaml`.
