### ISSUE TITLE
Preprocess for NW-UCLA

### ISSUE THREAD

**Issue by YanjunChen** [kchengiva/Shift-GCN#21]
Hi, thanks for your outstanding work.
Following your experimental setting, I got 90.52% for 1s shift GCN, it is much lower than the accuracy which is 92.5 reported in the paper. I am working with one K40 GPU.
I am wondering what has caused the difference, could you please enlighten me?
Thanks a lot!

**Comment by kchengiva** [comment]
Thanks for your interest. You can refer to [this](https://github.com/kchengiva/Shift-GCN/issues/13#issuecomment-718395974) for the data preprocessing.

**Comment by YanjunChen** [comment]
> Thanks for your interest. You can refer to [this](https://github.com/kchengiva/Shift-GCN/issues/13#issuecomment-718395974) for the data preprocessing.

Thanks for your reply. 
I am following the same preprocess and experimental setting mentioned. And the result is 90.52%, which is still a little bit lower.
Could you please tell me what kind of GPU are you using? Whether you are using parallel computing?

**Comment by kchengiva** [comment]
Thanks for your interest. We use one Titan XP GPU for NW-UCLA dataset. The performance difference may be caused by different environment or randomness of initialization, especially in small datasets.

**Comment by YanjunChen** [comment]
Thanks for your reply.
I will try with a Titan XP later.

**Comment by mbilalshaikh** [comment]
There are 10 actions for NW-UCLA, why you have chosen 28 in the config file. Could you please elaborate, I am finding it difficult to understand why the num of classes is 28?

**Comment by kchengiva** [comment]
Thank you for your correction @mbilalshaikh . The number of classes should be set to 10. Setting to 28 is a mistake, but it does not affect the results. We have corrected it.

**Comment by mbilalshaikh** [comment]
Thanks for this.
NW-UCLA dataset contains 12 action a01-12 but why are we considering ten classes? Shouldn't it be 12 classes?
