### ISSUE TITLE
training and testing

### ISSUE THREAD

**Issue by Nancyuru** [kchengiva/Shift-GCN#23]
Dear kchengiva，
Hello, I'm so sorry to bother you again. I have two questions now. I would appreciate it if you could help me. First, after running your code, I found that your model is training an epoch, verifying an epoch, without testing, right? Or test is the verification of every epoch. Second, I want to try to train ten epochs and verify one epoch. How should I modify the parameters? Thank you! Looking forward to your reply.

**Comment by kchengiva** [comment]
Thanks for your interest. Test is the verification of every epoch, and you can modify the code in `./main.py` L480-487 to change test frequency.
