### ISSUE TITLE
How can I extract the shift operation?

### ISSUE THREAD

**Issue by Lyndsey-Xing** [kchengiva/Shift-GCN#3]
Hello, your work is very meaningful,  I am interested in it.

1、I am confused about that 'Temporal_shift' folder. If I want to extract your shift-gcn (spatial and temporal), what should I do? Because I don't quite understand the contents of cuda related documents in 'Temporal_shift'.
2、Where can the code embody this module ‘Shift-Conv and Shift-Conv- Shift’？

Thanks

**Comment by kchengiva** [comment]
Thanks for your interest. 
The model of ShiftGCN is `./model/shift_gcn.py`. In this file, the class `Shift_gcn` is spatial shift GCN; the class `Shift_tcn` is temporal shift GCN.
For `Shift_gcn`, the `torch.einsum` operation is the point-wise convolution. Before it, we write a code commenting `shift1` (line125-129); after it, we write a code commenting `shift2` (line134-138). It is the spatial 'shift-conv-shift' structure.
For `Shift_tcn`, the `self.temporal_linear` operation is the point-wise convolution. Before it, we write a code commenting `shift1` (line67-68); after it, we write a code commenting `shift2` (line71-72). It is the temporal 'shift-conv-shift' structure.

**Comment by kchengiva** [comment]
Hello. The file in the `Temporal_shift` is a cuda extension for adaptive temporal shift operation, you do not need to modify it. If you want to use it, firstly you should compile it following our readme, then you can refer to `./model/shift_gcn.py` for the usage. You can only modify Shift_tcn, Shift_gcn.

**Comment by Lyndsey-Xing** [comment]
Thanks. This is of great help to me.
