### ISSUE TITLE
Trained models

### ISSUE THREAD

**Issue by vivek87799** [kchengiva/Shift-GCN#6]
Hi,
Thank you very much for the wonderful work and a well documented repository.
It would be very helpful if you could provide the trained model.

**Comment by kchengiva** [comment]
Thanks for your interest. We released several trained models in `./save_models/`.

**Comment by vivek87799** [comment]
Thank you very much for the reply.

**Comment by vivek87799** [comment]
Hi @kchengiva 

It will be very kind if you could also provide 2 stream trained model. It will be very helpful for my thesis.
Sorry for the trouble, it takes days on my system to train.

**Comment by kchengiva** [comment]
I'm sorry I couldn't be more helpful. We have deleted other saved models on our server.

**Comment by vivek87799** [comment]
Thank you for the reply.

**Comment by Lyndsey-Xing** [comment]
Hello @kchengiva 

I write the code like ./config/nturgbd-cross-subject/XXX.yaml to train the NTU 120 dataset, but my results can't achieve the results in the paper, and there is a certain gap.

Could you provide your . /config/XXX.yaml files of NTU120 and Kinetics? Thanks.

**Comment by kchengiva** [comment]
Hello. The `config` file of 1 stream NTU120 X-sub is as below. We have not trained on Kinetics.

```
Experiment_name: ntu120_ShiftGCN_joint_xsub

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu120/xsub/train_data_joint.npy
  label_path: ./data/ntu120/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/ntu120/xsub/val_data_joint.npy
  label_path: ./data/ntu120/xsub/val_label.pkl

# model
model: model.shift_gcn.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [60, 80, 100]

# training
device: [0,1,2,3]
only_train_epoch: 1
batch_size: 64
test_batch_size: 64
num_epoch: 140
nesterov: True
```

**Comment by Lyndsey-Xing** [comment]
@kchengiva Thanks for your help.
