### ISSUE TITLE
How do you compute the FLOPs of model?

### ISSUE THREAD

**Issue by xf1994** [kchengiva/Shift-GCN#7]
I calculate the flops using thop like:

from thop import profile
flops, params = profile(model, inputs = (x,))

is this the right way to compute the flops?

BTW, I computed the FLOPS of agcn and MSG3D (single model), and get the flops of them are around 18G and 24G. Is this the correct number?

**Comment by kchengiva** [comment]
Thanks for your interest. The code of some previous works are not publicly available (such as AGC-LSTM, Directed-GNN), whose FLOPs cannot be calculated by thop. Hence, we calculate the FLOPs of all models manually. Details are provided in supplement material. Our result of Shift-GCN and Adaptive-GCN are similar to the result calculated by thop.

**Comment by xf1994** [comment]
> Thanks for your interest. The code of some previous works are not publicly available (such as AGC-LSTM, Directed-GNN), whose FLOPs cannot be calculated by thop. Hence, we calculate the FLOPs of all models manually. Details are provided in supplement material. Our result of Shift-GCN and Adaptive-GCN are similar to the result calculated by thop.

**Comment by Lyndsey-Xing** [comment]
@xf1994 I also got 24GMACs of MS-G3D. First, unit of measurement
