### ISSUE TITLE
 processed N-UCLA data

### ISSUE THREAD

**Issue by huangzjn** [kchengiva/Shift-GCN#9]
Thank you very much for your work.If convenient,could you provide processed N-UCLA data. Thanks.

**Comment by kchengiva** [comment]
Thanks for your interest. The raw N-UCLA data can be downloaded [here](https://www.dropbox.com/s/10pcm4pksjy6mkq/all_sqe.zip?dl=0). You can refer to [this](https://github.com/kchengiva/Shift-GCN/issues/4) for the process of N-UCLA data.

**Comment by huangzjn** [comment]
OK! Thank you very much for your help.
